### ISSUE TITLE
Aux is no valid file name on Windows

### ISSUE THREAD

**Issue by reserschnell** [wkirgsn/thermal-nn#1]
Hi Wilhelm,
unfortunately, I cannot checkout your repo on my Windows machine. I'm pretty sure that the issue occurs because you have a folder called aux.
The issue is also described here:
https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl
Can you maybe rename the folder?

Regards
Andreas

**Comment by wkirgsn** [comment]
Hey, sorry for getting back to you this late.
I will change that no problem.

I do not cease from being surprised by what weird rules Windows applies to its users.

**Comment by wkirgsn** [comment]
Just renamed aux to tf2utils, it should work out now, can you confirm?

**Comment by reserschnell** [comment]
Hi, I've cloned the changes and cloning was working but the notebooks where not running for me. I'll provide a pull request next week and you can check my changes.

**Comment by reserschnell** [comment]
Which Python or tensorflow version are you using?
I've tried to use Python 3.11.5 with tensorflow 2.14.0, but it seems that tensorflow.keras.wrappers.scikit_learn is removed in this version.
You can get your tensorflow version with:
`pip show tensorflow `

**Comment by nMaroulis** [comment]
@reserschnell I had the same issue and solved that but installing the  scikeras library and replacing the import with 'from scikeras.wrappers import KerasRegressor' and it works fine.

**Comment by wkirgsn** [comment]
I guess I will look into implementing a modern Tensorflow implementation of the TNN, and then lock the version used in a requirements.txt

**Comment by reserschnell** [comment]
@nMaroulis thank you for the hint, I can give it a try.
@wkirgsn: It would be really great if you can create a consistent state of the repository. Maybe you can mark it then as a release, that everyone knows that this is a version everyone can start from.

**Comment by wkirgsn** [comment]
@reserschnell , @nMaroulis Just published a new initial release, with the tensorflow notebook drastically reduced to a minimal working example, in the same style as the pytorch example.

Closing this issue for now, but can be reopened in case of reoccurring issues
